version: "3"

# networks:

#   eos-blocks-graphql-api_default:
#     external:
#       name: eos-blocks-graphql-api_default

services:

  eosio:
    image: eosio/eos:dawn3x
    ports:
      - "8888:8888"
      - "9876:9876"
    command: /opt/eosio/bin/nodeosd.sh --resync-blockchain
    volumes:
      - ./eosio-volume/config:/opt/eosio/bin/data-dir
      - ./eosio-volume/data:/opt/eosio/var
    # logging:
    #   driver: none

  api-server:
    container_name: api-server
    build:
      context: ./api-server
      dockerfile: Dockerfile-server
    ports:
      - "3001:3001"
    links:
      - eosio
    volumes:
      - ./api-server:/usr/src/app

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

volumes:

  data: